#NumPy
Creación de arreglos (arrays), mayor eficiencia en memoria.

Los arrays pueden contener diferentes tipos de dato, pero ólo uno a la vez.

No necesitamos iterar sobre cada casilla, podemos pensar en los arrays como objetos (similar a R).



In [ ]:
#Importamos NumPy 
import numpy as np

array_1D = np.array([1,2,3])
array_1D

array([1, 2, 3])

In [ ]:
array_2D = np.array([ [1,2,3], (2,3,4)])
array_2D

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
array_3D = np.array([  [ [1, 2], [3, 4] ],   [ [5, 6], [7, 8] ]  ])
array_3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
### Biomasa E. coli ###

# Ingresamos la biomasa en unidades de absorbancia 
ecoli_matraz = np.array([0.1, 0.15, 0.19, 0.5, 
                         0.9, 1.4, 1.8, 2.1, 2.3])
print(ecoli_matraz.ndim)
print(ecoli_matraz.shape)
print(len(ecoli_matraz))

1
(9,)
9


In [ ]:
#Biomasa en unidades de absorbancia  (OD600)
ecoli_m_b = np.array([[0.1, 0.15, 0.19, 0.5,  #Matraz 250 mL
                       0.9, 1.4, 1.8, 2.1, 2.3],
                      [0.1, 0.17, 0.2, 0.53,  #Biorreactor 50 L
                       0.97, 1.43, 1.8, 2.1,  2.8],
                      [0.1, 0.17, 0.2, 0.52,  #B. alimentado 50 L
                       0.95, 1.41, 1.8, 2.2,  2.8] 
                      ])

print(ecoli_m_b.ndim)
print(ecoli_m_b.shape)
print(len(ecoli_m_b))

2
(3, 9)
3


In [ ]:
#Otra forma de hacerlo

array_1D = np.array((1,2,3))
print(array_1D.ndim)
print(array_1D.shape)
print(len(array_1D))

array_2D = np.array([ (1,2,3),(4,5,6) ])
print(array_2D.ndim)
print(array_2D.shape)
print(len(array_2D))

array_3D = np.array([ ([1,2], [3,4]),
                     ([5,6], [7,8]) ] )

1
(3,)
3
2
(2, 3)
2


In [ ]:
### Una OD600 de 1 representa 0.39 g/L de peso seco. ###

#Biomasa en unidades de absorbancia  (OD600)
# Valor original 1
ecoli_m_b = np.array([[0.1, 0.15, 0.19, 0.5,  #Matraz 250 mL
                       0.9, 1.4, 1.8, 2.1, 2.3],
                      [0.1, 0.17, 0.2, 0.53,  #Biorreactor 50 L
                       0.97, 1.43, 1.8, 2.1,  2.8],
                      [0.1, 0.17, 0.2, 0.52,  #B. alimentado 50 L
                       0.95, 1.41, 1.8, 2.2,  2.8] 
                      ])

#Valor *0.39
ecoli_matraz_gL = ecoli_m_b * 0.39
ecoli_matraz_gL

array([[0.039 , 0.0585, 0.0741, 0.195 , 0.351 , 0.546 , 0.702 , 0.819 ,
        0.897 ],
       [0.039 , 0.0663, 0.078 , 0.2067, 0.3783, 0.5577, 0.702 , 0.819 ,
        1.092 ],
       [0.039 , 0.0663, 0.078 , 0.2028, 0.3705, 0.5499, 0.702 , 0.858 ,
        1.092 ]])

##Operaciones

podemos aplicar operaciones directamente al objeto (se aplican en cada ítem del objeto)

In [ ]:
# ¿Cuál sería el total de mi producción si tengo 2 biorreactores?
produccion = np.array([[16, 14],  # 1 biorreactor
                       [12, 9]])
total = produccion*2
total = produccion + produccion

m = np.sum(produccion*2, axis= 0) # Por metabolito
b = np.sum(produccion*2, axis= 1) # Por bacteria

print(total)
print(m)
print(b)

[[32 28]
 [24 18]]
[56 46]
[60 42]


In [ ]:
#Al extraer el producto, se contaminó la mitad del líquido de uno de los biorreactores
contaminado = total/2
print(contaminado)

total_real = total-contaminado
print(total_real)

[[16. 14.]
 [12.  9.]]
[[16. 14.]
 [12.  9.]]


Para crear un fármaco, necesito las siguientes cantidades de los metabolitos de cada bacteria
```
	            Metabolito A	Metabolito B
Consumo bac1  	  7	              3
Consumo bac2	    5	              2
```



In [ ]:
#¿Cuánto producto me sobra?
consumo =  np.array([[7, 3],[5, 2]])
print(total_real)
total_real-consumo

[[16. 14.]
 [12.  9.]]


array([[ 9., 11.],
       [ 7.,  7.]])

In [ ]:
#¿Si se necesitara la misma cantidad por cada bacteria? 
#¿Cómo crearian ahora a la variable consumo?

consumo =  np.array([[7, 3],[7, 3]])
total_real - consumo  #Por bacteria

consumo =  np.array([7, 3])  #Al igual que en R, podemos reciclar:
total_real - consumo  #Por bacteria

array([[ 9., 11.],
       [ 5.,  6.]])

### Podemos aplicar otras funciones
* Potencia 
* Transpuesta y suma total
* Mínimo y máximo
* Exponencial y raíz cuadrada
* Trigonométricas
* Calcular y asignar
* Redondeo


In [ ]:
#Potencia
total_real**2
total_real**total_real

#transpuesta
total_real.T

#Suma total
total_real.sum()

#minimo y máximo
total_real.min() 
total_real.max()
np.max(total_real)

#Exponencial y raíz cuadrada
np.exp(total_real)
np.sqrt(total_real)

#Trigonométricas
np.sin(np.array([np.pi, np.pi/2]))
np.arcsin(np.array([0.0, 1.0]))

#Calcular y asignar
total_real += 2
total_real *= 2

#Redondeo
redondear = np.array([1.1, 1.5, 1.9, 2.5])
np.round(redondear)
np.floor(redondear)  #entero abajo
np.ceil(redondear)  #entero arriba


array([2., 2., 2., 3.])

## Ejercicio 1
Al inducir 4 genes de producción a diferentes temperaturas se obtuvieron las siguientes producciones del metabolito de interés en g/L:


```
	    30 °C 	35 °C
Gen1	   5    	3
Gen2	  11	    7
Gen3	   4	    9
Gen4	   2	    6
```
Cada gen tiene un inductor diferente y cada uno tuvo los siguientes costos:


```
	   Costo de inducción
Gen1	    3.5
Gen2	    5
Gen3	    7
Gen4	    4.3
```
¿Qué gen nos conviene inducir y a qué temperatura para obtener nuestro metabolito?






In [ ]:
produccion = np.array( [ [5,3], 
                        [11, 7], 
                        [4, 9], 
                        [2, 6] ])

costos = np.array([3.5, 5, 7, 4.3])

#Costo unitario de producir 1g/L metabolito
costo_unitario = (costos / produccion.T).T


### Tipos de dato 


In [ ]:
#Preguntar tipo de dato: dtype

from sys import getsizeof

np_float = np.array([1.0, 2.0, 3.0, 4.0])
print("Tipo de dato\t", np_float.dtype, 
"\nTamaño en bytes\t", getsizeof(np_float))

np_int = np.array([1, 2, 3, 4])
print("Tipo de dato\t", np_int.dtype, 
"\nTamaño en bytes\t", getsizeof(np_int))

Tipo de dato	 float64 
Tamaño en bytes	 128
Tipo de dato	 int64 
Tamaño en bytes	 128


In [ ]:
#Tambien podemos especificar/forzar tipos de dato

np_float = np.array([1, 2, 3, 4],
                    dtype='float64')
print("Tipo de dato\t", np_float.dtype, 
"\nTamaño en bytes\t", getsizeof(np_float))

np_int = np.array([1.0, 2.0, 3.0, 4.0],
                  dtype='int32')
print("Tipo de dato\t", np_int.dtype, 
"\nTamaño en bytes\t", getsizeof(np_int))

Tipo de dato	 float64 
Tamaño en bytes	 128
Tipo de dato	 int32 
Tamaño en bytes	 112


In [ ]:
### Tipo de dato booleano ### 
bool_np = np.array([True, False, True, False]) 
bool_np.dtype

#Accedemos con el array booleano
np_int


array([1, 2, 3, 4], dtype=int32)

In [ ]:
#Otros ejemplos de acceso con booleanos
np_int <3

array([ True,  True, False, False])

## Ejercicio 2
Del ejericio anterior, imprime el costo de producción más alto y el más bajo utilizando booleanos.

In [ ]:
menor_costo = costo_unitario.min()
mayor_costo = costo_unitario.max()

menor_costo_bol = costo_unitario == menor_costo
mayor_costo_bol = costo_unitario == mayor_costo

(mayor_costo_bol | menor_costo_bol)

array([[False, False],
       [ True, False],
       [False, False],
       [ True, False]])

In [ ]:
### Tipo de dato complejo ###

num_1 = np.array([3+6j])   
num_2 = np.array([7+2j])   
num_1.dtype

num_1.real  #parte real
num_1.imag  #parte imaginaria
num_1+num_2  #suma

In [ ]:
### Tipo de dato fecha: ISO 8601 o formato datetime ###

dias = np.datetime64('2005-02-25')
dias.dtype

dtype('<M8[D]')

In [ ]:
meses = np.datetime64('2005-02')
meses.dtype

dtype('<M8[M]')

In [ ]:
forzar_dias = np.datetime64('2005-02', 'D')
forzar_dias.dtype

dtype('<M8[D]')

In [ ]:
#Comparar fechas
np.datetime64('2005') == np.datetime64('2005-01-01')
#Cálculos con fechas
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')
np.datetime64('2009') + np.timedelta64(20, 'D')

### Acceder al array 1D

In [ ]:
print(ecoli_matraz)
print(ecoli_matraz[2])
print(ecoli_matraz[2:5])

# Del 0 al 6 de 2 en 2
ecoli_matraz[0:6:2] 


[0.1  0.15 0.19 0.5  0.9  1.4  1.8  2.1  2.3 ]
0.19
[0.19 0.5  0.9 ]


array([0.1 , 0.19, 0.9 ])

In [ ]:
#Regresa el array de forma reversa
ecoli_matraz[::-1]

array([2.3 , 2.1 , 1.8 , 1.4 , 0.9 , 0.5 , 0.19, 0.15, 0.1 ])

### Acceder al array 2D

In [ ]:
print(produccion)

print(produccion[2])
print(produccion[2:4])

# Del 0 al 6 de 2 en 2
print(produccion[0:6:2]) 

#produccion[0:6:2][1] no es igual que produccion[0:6:2, 1] *

[[ 5  3]
 [11  7]
 [ 4  9]
 [ 2  6]]
[4 9]
[[4 9]
 [2 6]]
[[5 3]
 [4 9]]


### usando '...'


In [ ]:
a_3D = np.array([[[  1,  2,  3],
               [ 11, 12, 13]],
              [[101, 102, 103],
               [1001, 1002, 1003]]])
a_3D[1, ...]  

array([[ 101,  102,  103],
       [1001, 1002, 1003]])

## Funciones para crear arrays arange y linspace

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#de cuanto en cuanto
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
#cuantos segmentos
np.linspace(0, 8, 5)

array([0., 2., 4., 6., 8.])

In [ ]:
### Random ###

np.random.randint(0, 10, 3)

array([3, 4, 4])

In [ ]:
### np.random.rand(3)

array([0.33051402, 0.4708511 , 0.86950958])

In [ ]:
### creación de distribuciones)
np.random.uniform(1, 10, 3)

array([2.22529215, 3.81822238, 7.58317239])

In [ ]:
np.random.normal(5, 2, 3)

array([7.95657453, 5.40279894, 2.77708117])

In [ ]:
np.random.poisson(10, 3)

array([10,  9, 10])

También podemos: hacer repeticiones, unir, dividir, borrar filas/columnas...

Existen diferencias entre arrays y listas (no son iguales)


# Array estructurado
creamos nuestras propias estructuras

In [ ]:
mascotas = np.array([('Freya', 6, 6.5), ('Senna', 1, 2.5)], 
                    dtype=[('nombre', (np.str_, 10)), ('edad', np.int32), ('peso', np.float64)])

sort_age = np.sort(mascotas, order='edad')
sort_name = np.sort(mascotas, order='nombre')

sort_age

array([('Senna', 1, 2.5), ('Freya', 6, 6.5)],
      dtype=[('nombre', '<U10'), ('edad', '<i4'), ('peso', '<f8')])